// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2unv5tNX8Dxq9F83_q9cNEh2--PBOYjY',
    appId: '1:1070034619711:web:b10abe6b0577433b52578a',
    messagingSenderId: '1070034619711',
    projectId: 'interprep-585db',
    authDomain: 'interprep-585db.firebaseapp.com',
    storageBucket: 'interprep-585db.firebasestorage.app',
    measurementId: 'G-BC208YTZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0akBz0IIo--UmDlwuJ7g6mb70-cX_gE',
    appId: '1:1070034619711:android:2830c41253b4e77852578a',
    messagingSenderId: '1070034619711',
    projectId: 'interprep-585db',
    storageBucket: 'interprep-585db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4aj4yF2-tBHxQ_Oc0gMmUhdo7Ku0aMNU',
    appId: '1:1070034619711:ios:d2eacd88d67c811252578a',
    messagingSenderId: '1070034619711',
    projectId: 'interprep-585db',
    storageBucket: 'interprep-585db.firebasestorage.app',
    iosBundleId: 'com.example.prepvrse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4aj4yF2-tBHxQ_Oc0gMmUhdo7Ku0aMNU',
    appId: '1:1070034619711:ios:d2eacd88d67c811252578a',
    messagingSenderId: '1070034619711',
    projectId: 'interprep-585db',
    storageBucket: 'interprep-585db.firebasestorage.app',
    iosBundleId: 'com.example.prepvrse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2unv5tNX8Dxq9F83_q9cNEh2--PBOYjY',
    appId: '1:1070034619711:web:a7b309222c118ced52578a',
    messagingSenderId: '1070034619711',
    projectId: 'interprep-585db',
    authDomain: 'interprep-585db.firebaseapp.com',
    storageBucket: 'interprep-585db.firebasestorage.app',
    measurementId: 'G-QL55ZDQB6E',
  );

}